import Button from "@mui/joy/Button";
import {Typography} from "@mui/joy";
import Grid from '@mui/material/Grid';
//import React, {useState} from "react";
import Box from '@mui/material/Box';
import Header from "../discover/header";
import "../discover/discover.css"


export default async function Discover() {

    return (
        <div className="App">
            <Header></Header>
            <div className="box">
                <h1>Recommendation Generator with Feedback:</h1>
                <h2>Give us your feedback on the playlists generated by our AI and we will
                    readjust our parameters to better fit your needs!</h2>
            </div>

            <Box className="box">
                <div className="slide-text">
                    <h2>Happy:&nbsp;&nbsp;</h2>
                    <input type="range" className="slider"></input>
                </div>
                <Grid container spacing={2}>
                </Grid>
                <div className="slide-text">
                    <h2>Sad:&nbsp;&nbsp;</h2>
                    <input type="range" className="slider"></input>
                </div>
                <Grid container spacing={2} >
                </Grid>
                <div className="slide-text">
                    <h2>Angry:&nbsp;&nbsp;</h2>
                    <input type="range" className="slider"></input>
                </div>
                <Grid container spacing={2} >
                </Grid>
                <div className="slide-text">
                    <h2>Relaxed:&nbsp;&nbsp;</h2>
                    <input type="range" className="slider"></input>
                </div>
                <Grid container spacing={2} >
                </Grid>
            </Box>
            <Button variant="contained" className="button" size="large">Submit</Button>
            <Box className="box">
                    <p>Placeholder for Form</p>
            </Box>
        </div>
    );
}